spring.application.name=FLiigaFantasy
spring.datasource.url=jdbc:postgresql://localhost:5432/fliiga
spring.datasource.username=hagelino
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
